name: dockerbuild

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # -
      #   name: check files
      #   shell: bash
      #   run: |
      #     ls
      - 
        name: build on docker
        uses: docker/build-push-action@v3
        # with:
          # push: false
