name: ci

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # -
      #   name: check files
      #   shell: bash
      #   run: |
      #     ls
      - 
        name: build on docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: elangelo/fotodirbrowser:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
